# Use postgres/example user/password credentials
version: '3.1'

services:

  SmartBoardWebAPI:
    image: smartboardwebapi
    build:
      context: .
      dockerfile: SmartBoardWebAPI/Dockerfile
    ports:
      - "7068:80"
    networks:
      - smartboard-network
    environment:
      - ASPNETCORE_HTTPS_PORT=7068

volumes:
  db:
networks: 
    smartboard-network:
