# Use postgres/example user/password credentials
version: '3.1'

services:

  SmartBoardDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgrespw"
    ports: 
      - "7777:5432"
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/teste.sql
  SmartBoardWebAPI:
    image: smartboardwebapi
    build:
      context: .
    ports:
      - "20000:80"
    networks:
      - smartboard-network
volumes:
  db:
    driver: local
networks: 
    smartboard-network:
        driver: bridge
