# Use postgres/example user/password credentials
version: '3.1'

services:

  SmartBoardDB:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=smarboarddb
    ports: 
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/
  SmartBoardWebAPI:
    image: smartboardwebapi
    build:
      context: .
    ports:
      - "32777:80"
    networks:
      - smartboard-network

volumes:
  db:
    driver: local
networks: 
    smartboard-network:
        driver: bridge
